ALTER TABLE IF EXISTS department
    ALTER COLUMN short_name DROP NOT NULL,
    ALTER COLUMN full_name DROP NOT NULL,
    ALTER COLUMN address DROP NOT NULL,
    ALTER COLUMN external_id DROP NOT NULL,
    ALTER COLUMN phone DROP NOT NULL;