services:

  minio:
    container_name: minio
    image: bitnami/minio:latest
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    container_name: postgres
    image: postgres:12.14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oog
      POSTGRES_DB: edo_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: edo_db
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: oog
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"