spring:
  application:
    name: edo-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
geocodeMapsYandex:
  url: "https://geocode-maps.yandex.ru/1.x/?format=json&results=1&sco=longlat&apikey=9fdbb2aa-5f75-43e0-ae21-491b46864d11&geocode="
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: info